import { createClient } from "~/utils/supabase/server";
import { cookies } from "next/headers";
import Link from "next/link";
import { ArrowLeft, Database, AlertCircle, CheckCircle2, ListTodo } from "lucide-react";

interface Todo {
  id: string | number;
  name?: string;
  title?: string;
  is_complete?: boolean;
}

export default async function Page() {
  const cookieStore = await cookies();
  const supabase = createClient(cookieStore);

  let todos: Todo[] | null = null;
  let errorMsg: string | null = null;

  try {
    const { data, error } = await supabase.from("todos").select();
    if (error) {
      errorMsg = error.message;
    } else {
      todos = data as Todo[];
    }
  } catch (err: unknown) {
    errorMsg = err instanceof Error ? err.message : "Failed to query Supabase";
  }

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-6 md:p-12 transition-colors">
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Navigation & Header */}
        <div className="flex items-center justify-between">
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-2 text-xs font-semibold text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Dashboard</span>
          </Link>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
            <Database className="w-3.5 h-3.5" />
            <span>Supabase Online</span>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 md:p-8 shadow-xs space-y-6">
          <div>
            <div className="flex items-center gap-2">
              <ListTodo className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              <h1 className="text-xl font-bold text-slate-900 dark:text-white">Supabase Integration Demo</h1>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
              Live server component query using <code className="font-mono bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded text-slate-700 dark:text-slate-300">createClient(cookieStore)</code> from <code className="font-mono bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded text-slate-700 dark:text-slate-300">~/utils/supabase/server</code>.
            </p>
          </div>

          {/* Error State */}
          {errorMsg ? (
            <div className="p-4 rounded-xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800 text-amber-800 dark:text-amber-200 space-y-2">
              <div className="flex items-center gap-2 font-semibold text-xs text-amber-900 dark:text-amber-200">
                <AlertCircle className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0" />
                <span>Table Query Note</span>
              </div>
              <p className="text-xs text-amber-800 dark:text-amber-300 leading-relaxed">
                {errorMsg}
              </p>
              <div className="pt-2 border-t border-amber-200/60 dark:border-amber-800/60 text-[11px] text-amber-700 dark:text-amber-300">
                Tip: If you haven&apos;t created the <code className="font-mono font-semibold">todos</code> table in Supabase yet, you can run:
                <pre className="mt-1.5 p-2.5 bg-white/80 dark:bg-slate-950 rounded-lg text-slate-800 dark:text-slate-200 font-mono text-[10px] overflow-x-auto border border-amber-200 dark:border-amber-800">
{`create table todos (
  id bigint generated by default as identity primary key,
  name text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);`}
                </pre>
              </div>
            </div>
          ) : todos && todos.length > 0 ? (
            /* Filled / Success State */
            <div className="space-y-3">
              <h2 className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                Todos from Supabase ({todos.length})
              </h2>
              <ul className="divide-y divide-slate-100 dark:divide-slate-800 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/50 overflow-hidden">
                {todos.map((todo) => (
                  <li key={todo.id} className="p-3.5 flex items-center gap-3 text-xs text-slate-800 dark:text-slate-200">
                    <CheckCircle2 className="w-4 h-4 text-emerald-500 dark:text-emerald-400 shrink-0" />
                    <span className="font-medium">{todo.name ?? todo.title ?? `Todo #${todo.id}`}</span>
                  </li>
                ))}
              </ul>
            </div>
          ) : (
            /* Empty State */
            <div className="text-center py-10 px-4 rounded-xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 space-y-3">
              <div className="w-10 h-10 rounded-full bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 flex items-center justify-center mx-auto">
                <ListTodo className="w-5 h-5" />
              </div>
              <div className="space-y-1">
                <h3 className="text-xs font-bold text-slate-800 dark:text-white">Connected to Supabase</h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 max-w-sm mx-auto">
                  The connection succeeded, but no records were found in the <code className="font-mono bg-slate-200 dark:bg-slate-800 px-1 py-0.5 rounded text-slate-700 dark:text-slate-300">todos</code> table.
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
